#
# @Project: @cldmv/wisp
# @Filename: /.github/workflows/publish.yml
# @Date: 2025-10-30 15:13:04 -07:00 (1761862384)
# @Author: Nate Hyson <CLDMV>
# @Email: <Shinrai@users.noreply.github.com>
# -----
# @Last modified by: Nate Hyson <CLDMV> (Shinrai@users.noreply.github.com)
# @Last modified time: 2025-10-30 15:14:07 -07:00 (1761862447)
# -----
# @Copyright: Copyright (c) 2013-2025 Catalyzed Motivation Inc. All rights reserved.
#


# Individual repo: .github/workflows/publish.yml
name: 📦 Release and Publish

on:
    pull_request:
        types: [closed]
        branches: [master, main]
    workflow_dispatch:
        inputs:
            debug:
                description: "Enable debug logging for troubleshooting"
                type: boolean
                required: false
                default: false
            dry_run:
                description: "Dry run mode - validate everything but don't publish or create releases"
                type: boolean
                required: false
                default: false
            node_version:
                description: "Node.js version to use (default: lts/*)"
                type: string
                required: false
                default: "lts/*"
            package_manager:
                description: "Package manager (npm or yarn)"
                type: string
                required: false
                default: "npm"
            version:
                description: "Version to publish (auto-detected from package.json if not provided)"
                type: string
                required: false
                default: ""
            publish_to_npm:
                description: "Publish to NPM registry"
                type: boolean
                required: false
                default: true
            publish_to_github_packages:
                description: "Publish to GitHub Packages registry"
                type: boolean
                required: false
                default: true
            min_node_version:
                description: "Minimum Node.js version for matrix testing (enables matrix when set)"
                type: string
                required: false
                default: "20"
            max_node_major:
                description: "Override max Node.js major version (default: 22)"
                type: string
                required: false
                default: "22"
            use_gpg:
                description: "Enable GPG signing (if GPG secrets provided)"
                type: boolean
                required: false
                default: false

jobs:
    publish-package:
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        uses: CLDMV/.github/.github/workflows/workflow-publish.yml@v1
        with:
            package_name: "@cldmv/slothlet" # Required: Your NPM package name
            debug: ${{ github.event.inputs.debug == 'true' }}
            dry_run: ${{ github.event.inputs.dry_run == 'true' }}
            node_version: ${{ github.event.inputs.node_version || 'lts/*' }}
            package_manager: ${{ github.event.inputs.package_manager || 'npm' }}
            version: ${{ github.event.inputs.version || '' }}
            publish_to_npm: ${{ github.event.inputs.publish_to_npm != 'false' }}
            publish_to_github_packages: ${{ github.event.inputs.publish_to_github_packages != 'false' }}
            publish_command: ""
            github_packages_publish_command: ""
            min_node_version: ${{ github.event.inputs.min_node_version || '16.14' }}
            max_node_major: ${{ github.event.inputs.max_node_major || '22' }}
            test_command: "npm test"
            build_command: "npm run build:ci"
            is_prerelease: false
            release_source_only: false
            create_documentation: true
            skip_performance_tests: false
            skip_matrix_tests: false
            use_gpg: ${{ github.event.inputs.use_gpg == 'true' }}
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            BOT_APP_ID: ${{ secrets.CLDMV_BOT_APP_ID }}
            BOT_APP_PRIVATE_KEY: ${{ secrets.CLDMV_BOT_APP_PRIVATE_KEY }}
            TAGGER_NAME: ${{ secrets.CLDMV_BOT_NAME }}
            TAGGER_EMAIL: ${{ secrets.CLDMV_BOT_EMAIL }}
            GPG_PRIVATE_KEY: ${{ secrets.CLDMV_BOT_GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.CLDMV_BOT_GPG_PASSPHRASE }}
