#
# @Project: @cldmv/wisp
# @Filename: /.github/workflows/release.yml
# @Date: 2025-10-30 15:13:04 -07:00 (1761862384)
# @Author: Nate Hyson <CLDMV>
# @Email: <Shinrai@users.noreply.github.com>
# -----
# @Last modified by: Nate Hyson <CLDMV> (Shinrai@users.noreply.github.com)
# @Last modified time: 2025-10-30 15:14:12 -07:00 (1761862452)
# -----
# @Copyright: Copyright (c) 2013-2025 Catalyzed Motivation Inc. All rights reserved.
#


# Individual repo: .github/workflows/release.yml
#
# This workflow intelligently detects release commits in the commit history
# and creates release PRs. It runs on human commits to branches (except main/master)
# and uses smart commit analysis to determine if a release should be created.
# Bot commits are ignored to prevent infinite loops.
#
name: 🚀 Create Release PR

on:
    push:
        branches-ignore: [master, main]
        paths-ignore:
            - "**.md"
            - "docs/**"
    workflow_dispatch:
        inputs:
            debug:
                description: "Enable debug logging for troubleshooting"
                type: boolean
                required: false
                default: false
            dry_run:
                description: "Dry run mode - validate everything but don't create PR or make changes"
                type: boolean
                required: false
                default: false
            node_version:
                description: "Node.js version to use (default: lts/*)"
                type: string
                required: false
                default: "lts/*"
            min_node_version:
                description: "Minimum Node.js version for matrix testing (default: 20, oldest non-EOL)"
                type: string
                required: false
                default: "20"
            max_node_major:
                description: "Override max Node.js major version (default: 22)"
                type: string
                required: false
                default: "22"
            package_manager:
                description: "Package manager (npm or yarn)"
                type: string
                required: false
                default: "npm"
            version_bump:
                description: "Type of version bump (major, minor, patch). Leave empty for auto-detection from commit message."
                type: string
                required: false
                default: ""
            version:
                description: "Specific version for release (auto-calculated if not provided)"
                type: string
                required: false
                default: ""
            is_prerelease:
                description: "Whether this is a prerelease"
                type: boolean
                required: false
                default: false
            create_documentation:
                description: "Whether to create/update VERSION_TAGS.md"
                type: boolean
                required: false
                default: true

jobs:
    create-release-pr:
        # Prevent infinite loops: Don't run on bot commits or if PR already exists
        if: |
            github.actor != 'cldmv-bot[bot]' && 
            github.actor != 'github-actions[bot]' &&
            !startsWith(github.event.head_commit.message, 'chore: bump version')
        uses: CLDMV/.github/.github/workflows/workflow-release.yml@v1
        with:
            package_name: "@cldmv/slothlet" # Required: Your NPM package name
            debug: ${{ github.event.inputs.debug == 'true' }}
            dry_run: ${{ github.event.inputs.dry_run == 'true' }}
            node_version: ${{ github.event.inputs.node_version || 'lts/*' }}
            min_node_version: ${{ github.event.inputs.min_node_version || '16.14' }}
            max_node_major: ${{ github.event.inputs.max_node_major || '22' }}
            package_manager: ${{ github.event.inputs.package_manager || 'npm' }}
            test_command: "npm test"
            build_command: "npm run build:ci"
            version_bump: ${{ github.event.inputs.version_bump || '' }}
            version: ${{ github.event.inputs.version || '' }}
            is_prerelease: ${{ github.event.inputs.is_prerelease == 'true' }}
            release_source_only: false
            create_documentation: ${{ github.event.inputs.create_documentation != 'false' }}
            skip_performance_tests: false
            skip_matrix_tests: false

        # Authentication & Bot Configuration
        # The workflow supports automatic App token detection for enhanced permissions and proper attribution:
        # - WITH App secrets: Operations attributed to CLDMV bot, enhanced permissions for workflow repositories
        # - WITHOUT App secrets: Falls back to GitHub Actions bot with standard permissions
        # To set up App authentication, add these secrets to your repository settings:
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            # CLDMV Bot credentials for enhanced permissions and proper attribution
            # Uncomment these lines to use your bot instead of github-actions[bot]
            BOT_APP_ID: ${{ secrets.CLDMV_BOT_APP_ID }}
            BOT_APP_PRIVATE_KEY: ${{ secrets.CLDMV_BOT_APP_PRIVATE_KEY }}
            # Optional: GPG signing credentials (only needed if use_gpg: true)
            TAGGER_NAME: ${{ secrets.CLDMV_BOT_NAME }}
            TAGGER_EMAIL: ${{ secrets.CLDMV_BOT_EMAIL }}
            GPG_PRIVATE_KEY: ${{ secrets.CLDMV_BOT_GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.CLDMV_BOT_GPG_PASSPHRASE }}
